#! /bin/bash

# ===================
# Script funtionality
# ===================

# do something
xfer() {
    echo 'doing something'
    show_submenus
}

show_submenus() {
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo " Choose Wisely"
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo "  1. util/transfer.sh "
    echo "  2. Custom"
    echo ""
}
# ================
# Script structure
# ================

# Show usage via commandline arguments
usage() {
  echo "~~~~~~~~~~~"
  echo " U S A G E"
  echo "~~~~~~~~~~~"
  echo "Usage: ./example.sh [option]"
  echo "  options:"
  echo "    -d : do something"
  echo "    -m : Show interactive menu"
  echo "    -h : Show this help"
  echo ""
  exit
}

# Function to display menu options
show_menus() {
    clear
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo " Main Menu"
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo "  1. Transfer Files"
    echo "  ---"
    echo "  x. Exit"
    echo ""
}

# Function to read menu input selection and take a action
read_options(){
    local choice
    read -p "Enter choice [ 1 - 2 ] " choice
    case $choice in
    1) xferxxx;;
    x) exit 0;;
    *) echo -e "${RED}Error...${STD}" && sleep 2
    esac
}

# Use menu...
do_menu() {
  # Main menu handler loop
  while true
  do
    show_menus
    read_options
  done
}

# If no arguments provided, display usage information
[[ $# -eq 0 ]] && usage

# Process command line arguments
if [[ $@ ]]; then
  while getopts "dmh" opt; do
    case $opt in
      d)
        doSomething
        shift
        ;;
      m)
      	do_menu
        shift
        ;;
      h)
        usage
        exit 0
        ;;
      \?)
        ;;
    esac
  done
else
  usage
  exit 0
fi
